# Generated by Django 3.2 on 2021-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cin', models.IntegerField()),
                ('Nom_electeur', models.CharField(max_length=512)),
                ('Date_Naissance', models.DateField()),
                ('Titre', models.CharField(max_length=4000)),
                ('Nb_vote', models.IntegerField(blank=True)),
            ],
        ),
    ]
