# Generated by Django 3.2 on 2021-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electeur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electeur',
            name='Nb_vote',
        ),
        migrations.AddField(
            model_name='electeur',
            name='Voter',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
