# Generated by Django 3.2 on 2021-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_condidat', models.CharField(max_length=512)),
                ('Cin', models.IntegerField()),
                ('Date_Naissance', models.DateField()),
                ('Titre', models.CharField(max_length=4000)),
                ('Objectif', models.CharField(max_length=4000)),
                ('Description', models.CharField(max_length=4000)),
                ('Nb_vote', models.IntegerField(blank=True)),
                ('Images', models.ManyToManyField(blank=True, to='condidat.Images')),
            ],
        ),
    ]
