# Generated by Django 3.2 on 2021-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidat',
            name='Nb_vote',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
