# Generated by Django 3.2 on 2021-12-26 12:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidat', '0002_alter_condidat_nb_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='Images',
            field=models.ManyToManyField(to='condidat.Images'),
        ),
    ]
