# Generated by Django 3.2 on 2021-12-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidat', '0003_auto_20211226_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidat',
            name='Images',
        ),
        migrations.AddField(
            model_name='condidat',
            name='Images',
            field=models.ImageField(blank=True, upload_to='Election/'),
        ),
    ]
