# Generated by Django 3.2 on 2022-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidat', '0005_auto_20211226_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidat',
            name='Experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='Titre',
            field=models.CharField(max_length=1024),
        ),
    ]
