# Generated by Django 3.2 on 2022-01-17 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condidat', '0006_auto_20220117_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidat',
            name='Images',
        ),
        migrations.AddField(
            model_name='condidat',
            name='Image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Images'),
        ),
    ]
